# Generated by Django 4.2.7 on 2025-08-08 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xx_notification',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='xx_userlevel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
