# Generated by Django 5.2.1 on 2025-08-18 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_and_entitys', '0006_alter_xx_account_entity_limit_is_transer_allowed_and_more'),
        ('user_management', '0002_alter_xx_notification_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xx_user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('superadmin', 'SuperAdmin')], max_length=10),
        ),
        migrations.CreateModel(
            name='xx_UserAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(blank=True, choices=[('edit', 'edit'), ('approve', 'approve')], max_length=50, null=True)),
                ('Entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_abilities', to='account_and_entitys.xx_entity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'XX_USER_ABILITY_XX',
                'unique_together': {('user', 'Entity', 'Type')},
            },
        ),
    ]
