# Generated by Django 5.2 on 2025-07-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MainCurrency",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon URL or class name for the currency",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Main Currency",
                "verbose_name_plural": "Main Currencies",
                "db_table": "main_currency",
            },
        ),
        migrations.CreateModel(
            name="MainRoutesName",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("english_name", models.CharField(max_length=255)),
                ("arabic_name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Main Route Name",
                "verbose_name_plural": "Main Routes Names",
                "db_table": "main_routes_name",
            },
        ),
    ]
