# Generated by Django 5.2 on 2025-07-30 10:05

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("budget_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="xx_TransactionTransfer",
            fields=[
                ("transfer_id", models.AutoField(primary_key=True, serialize=False)),
                ("cost_center_code", models.TextField(blank=True, null=True)),
                (
                    "account_name",
                    encrypted_model_fields.fields.EncryptedTextField(
                        blank=True, null=True
                    ),
                ),
                (
                    "approved_budget",
                    encrypted_model_fields.fields.EncryptedTextField(
                        blank=True, null=True
                    ),
                ),
                (
                    "available_budget",
                    encrypted_model_fields.fields.EncryptedTextField(
                        blank=True, null=True
                    ),
                ),
                ("from_center", models.TextField(blank=True, null=True)),
                ("to_center", models.TextField(blank=True, null=True)),
                (
                    "reason",
                    encrypted_model_fields.fields.EncryptedTextField(
                        blank=True, null=True
                    ),
                ),
                ("account_code", models.TextField(blank=True, null=True)),
                (
                    "cost_center_name",
                    encrypted_model_fields.fields.EncryptedTextField(
                        blank=True, null=True
                    ),
                ),
                ("done", models.IntegerField(default=1)),
                (
                    "encumbrance",
                    encrypted_model_fields.fields.EncryptedTextField(
                        blank=True, null=True
                    ),
                ),
                (
                    "actual",
                    encrypted_model_fields.fields.EncryptedTextField(
                        blank=True, null=True
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="adjd_transfers/"
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        db_column="transaction_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjd_transfers",
                        to="budget_management.xx_budgettransfer",
                    ),
                ),
            ],
            options={
                "db_table": "XX_Transaction_Transfer_XX",
            },
        ),
    ]
