# Generated by Django 5.2 on 2025-07-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adjd_transaction", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="xx_transactiontransfer",
            name="account_code",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="xx_transactiontransfer",
            name="cost_center_code",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
