# Generated by Django 4.2.7 on 2025-08-08 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adjd_transaction', '0002_alter_xx_transactiontransfer_account_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xx_transactiontransfer',
            name='account_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xx_transactiontransfer',
            name='actual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='xx_transactiontransfer',
            name='approved_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='xx_transactiontransfer',
            name='available_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='xx_transactiontransfer',
            name='cost_center_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xx_transactiontransfer',
            name='encumbrance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='xx_transactiontransfer',
            name='from_center',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='xx_transactiontransfer',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xx_transactiontransfer',
            name='to_center',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
