# Generated by Django 5.2 on 2025-07-30 10:05

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="xx_BudgetTransfer",
            fields=[
                ("transaction_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "transaction_date",
                    encrypted_model_fields.fields.EncryptedCharField(),
                ),
                ("amount", encrypted_model_fields.fields.EncryptedCharField()),
                ("status", encrypted_model_fields.fields.EncryptedCharField()),
                ("requested_by", encrypted_model_fields.fields.EncryptedCharField()),
                ("user_id", models.IntegerField(blank=True, null=True)),
                (
                    "request_date",
                    encrypted_model_fields.fields.EncryptedDateTimeField(
                        auto_now_add=True
                    ),
                ),
                (
                    "notes",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, null=True
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "gl_posting_status",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, null=True
                    ),
                ),
                (
                    "approvel_1",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, null=True
                    ),
                ),
                (
                    "approvel_2",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, null=True
                    ),
                ),
                (
                    "approvel_3",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, null=True
                    ),
                ),
                (
                    "approvel_4",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, null=True
                    ),
                ),
                (
                    "approvel_1_date",
                    encrypted_model_fields.fields.EncryptedDateTimeField(
                        blank=True, null=True
                    ),
                ),
                (
                    "approvel_2_date",
                    encrypted_model_fields.fields.EncryptedDateTimeField(
                        blank=True, null=True
                    ),
                ),
                (
                    "approvel_3_date",
                    encrypted_model_fields.fields.EncryptedDateTimeField(
                        blank=True, null=True
                    ),
                ),
                (
                    "approvel_4_date",
                    encrypted_model_fields.fields.EncryptedDateTimeField(
                        blank=True, null=True
                    ),
                ),
                ("status_level", models.IntegerField(default=1)),
                (
                    "attachment",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, default="No", null=True
                    ),
                ),
                (
                    "fy",
                    encrypted_model_fields.fields.EncryptedIntegerField(
                        blank=True, null=True
                    ),
                ),
                ("group_id", models.IntegerField(blank=True, null=True)),
                ("interface_id", models.IntegerField(blank=True, null=True)),
                ("reject_group_id", models.IntegerField(blank=True, null=True)),
                ("reject_interface_id", models.IntegerField(blank=True, null=True)),
                ("approve_group_id", models.IntegerField(blank=True, null=True)),
                ("approve_interface_id", models.IntegerField(blank=True, null=True)),
                (
                    "report",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, null=True
                    ),
                ),
                (
                    "type",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, null=True
                    ),
                ),
            ],
            options={
                "db_table": "XX_BUDGET_TRANSFER_XX",
            },
        ),
        migrations.CreateModel(
            name="xx_BudgetTransferAttachment",
            fields=[
                ("attachment_id", models.AutoField(primary_key=True, serialize=False)),
                ("file_name", encrypted_model_fields.fields.EncryptedCharField()),
                ("file_type", encrypted_model_fields.fields.EncryptedCharField()),
                ("file_size", models.IntegerField()),
                ("file_data", models.BinaryField()),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                (
                    "budget_transfer",
                    models.ForeignKey(
                        db_column="transaction_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="budget_management.xx_budgettransfer",
                    ),
                ),
            ],
            options={
                "db_table": "XX_BUDGET_TRANSFER_ATTACHMENT_XX",
            },
        ),
        migrations.CreateModel(
            name="xx_BudgetTransferRejectReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason_text",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, null=True
                    ),
                ),
                (
                    "reject_date",
                    encrypted_model_fields.fields.EncryptedDateTimeField(
                        auto_now_add=True
                    ),
                ),
                (
                    "reject_by",
                    encrypted_model_fields.fields.EncryptedCharField(blank=True),
                ),
                (
                    "Transcation_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reject_reasons",
                        to="budget_management.xx_budgettransfer",
                    ),
                ),
            ],
            options={
                "db_table": "XX_BUDGET_TRANSFER_REJECT_REASON_XX",
            },
        ),
    ]
