# Generated by Django 5.2 on 2025-07-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="xx_budgettransfer",
            name="request_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
