# Generated by Django 5.2 on 2025-07-30 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("budget_management", "0002_alter_xx_budgettransfer_request_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="xx_budgettransfer",
            name="requested_by",
        ),
    ]
