# Generated by Django 5.2 on 2025-07-30 17:36

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("budget_management", "0003_remove_xx_budgettransfer_requested_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="xx_budgettransfer",
            name="requested_by",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, null=True
            ),
        ),
    ]
