# Generated by Django 5.2 on 2025-08-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget_management", "0004_xx_budgettransfer_requested_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="xx_budgettransfer",
            name="status",
            field=models.CharField(max_length=10),
        ),
    ]
