# Generated by Django 4.2.7 on 2025-08-06 20:17

from django.db import migrations, models
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('budget_management', '0005_alter_xx_budgettransfer_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='xx_DashboardBudgetTransfer',
            fields=[
                ('Dashboard_id', models.AutoField(primary_key=True, serialize=False)),
                ('data', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('date', encrypted_model_fields.fields.EncryptedDateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'XX_DASHBOARD_BUDGET_TRANSFER_XX',
            },
        ),
    ]
