# Generated by Django 4.2.7 on 2025-08-08 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_management', '0006_xx_dashboardbudgettransfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xx_budgettransfer',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='xx_budgettransfer',
            name='approvel_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xx_budgettransfer',
            name='approvel_1_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xx_budgettransfer',
            name='approvel_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xx_budgettransfer',
            name='approvel_2_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xx_budgettransfer',
            name='approvel_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xx_budgettransfer',
            name='approvel_3_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xx_budgettransfer',
            name='approvel_4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xx_budgettransfer',
            name='approvel_4_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xx_budgettransfer',
            name='attachment',
            field=models.CharField(blank=True, default='No', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='xx_budgettransfer',
            name='fy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xx_budgettransfer',
            name='gl_posting_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='xx_budgettransfer',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xx_budgettransfer',
            name='report',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='xx_budgettransfer',
            name='requested_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xx_budgettransfer',
            name='transaction_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='xx_budgettransfer',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='xx_budgettransferattachment',
            name='file_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='xx_budgettransferattachment',
            name='file_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xx_budgettransferrejectreason',
            name='reason_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xx_budgettransferrejectreason',
            name='reject_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='xx_budgettransferrejectreason',
            name='reject_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='xx_dashboardbudgettransfer',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xx_dashboardbudgettransfer',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
