# Generated by Django 4.2.7 on 2025-08-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_management', '0007_alter_xx_budgettransfer_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xx_budgettransfer',
            name='transaction_date',
            field=models.CharField(max_length=10),
        ),
    ]
