# Generated by Django 5.2 on 2025-07-30 10:05

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="XX_Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account", models.CharField(max_length=255, unique=True)),
                (
                    "parent",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, null=True
                    ),
                ),
                (
                    "alias_default",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, null=True
                    ),
                ),
            ],
            options={
                "db_table": "XX_Account_XX",
            },
        ),
        migrations.CreateModel(
            name="XX_Entity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity", models.CharField(max_length=50)),
                (
                    "parent",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, null=True
                    ),
                ),
                (
                    "alias_default",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, null=True
                    ),
                ),
            ],
            options={
                "db_table": "XX_Entity_XX",
            },
        ),
        migrations.CreateModel(
            name="XX_TransactionAudit",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(blank=True, max_length=50, null=True)),
                ("transfer_id", models.IntegerField(blank=True, null=True)),
                (
                    "transcation_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "cost_center_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "account_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
            options={
                "db_table": "XX_TRANSACTION_AUDIT_XX",
            },
        ),
        migrations.CreateModel(
            name="XX_ACCOUNT_ENTITY_LIMIT",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("account_id", models.CharField(max_length=255)),
                ("entity_id", models.CharField(max_length=255)),
                (
                    "is_transer_allowed_for_source",
                    encrypted_model_fields.fields.EncryptedBooleanField(
                        blank=True, null=True
                    ),
                ),
                (
                    "is_transer_allowed_for_target",
                    encrypted_model_fields.fields.EncryptedBooleanField(
                        blank=True, null=True
                    ),
                ),
                (
                    "is_transer_allowed",
                    encrypted_model_fields.fields.EncryptedBooleanField(
                        blank=True, null=True
                    ),
                ),
                (
                    "source_count",
                    encrypted_model_fields.fields.EncryptedIntegerField(
                        blank=True, null=True
                    ),
                ),
                (
                    "target_count",
                    encrypted_model_fields.fields.EncryptedIntegerField(
                        blank=True, null=True
                    ),
                ),
            ],
            options={
                "db_table": "XX_ACCOUNT_ENTITY_LIMIT_XX",
                "unique_together": {("account_id", "entity_id")},
            },
        ),
        migrations.CreateModel(
            name="XX_PivotFund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity", models.CharField(max_length=50)),
                ("account", models.CharField(max_length=50)),
                ("year", models.IntegerField()),
                (
                    "actual",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, null=True
                    ),
                ),
                (
                    "fund",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, null=True
                    ),
                ),
                (
                    "budget",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, null=True
                    ),
                ),
                (
                    "encumbrance",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, null=True
                    ),
                ),
            ],
            options={
                "db_table": "XX_PivotFund_XX",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("entity", "account", "year"),
                        name="unique_entity_account_year",
                    )
                ],
            },
        ),
    ]
