# Generated by Django 5.2 on 2025-07-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_and_entitys", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="xx_pivotfund",
            name="account",
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name="xx_pivotfund",
            name="entity",
            field=models.IntegerField(max_length=50),
        ),
    ]
