# Generated by Django 5.2 on 2025-07-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "account_and_entitys",
            "0002_alter_xx_pivotfund_account_alter_xx_pivotfund_entity",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="xx_pivotfund",
            name="account",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="xx_pivotfund",
            name="entity",
            field=models.IntegerField(),
        ),
    ]
