# Generated by Django 4.2.7 on 2025-08-08 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_and_entitys', '0003_alter_xx_pivotfund_account_alter_xx_pivotfund_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xx_account',
            name='alias_default',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='xx_account',
            name='parent',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='xx_account_entity_limit',
            name='is_transer_allowed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xx_account_entity_limit',
            name='is_transer_allowed_for_source',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xx_account_entity_limit',
            name='is_transer_allowed_for_target',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xx_account_entity_limit',
            name='source_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xx_account_entity_limit',
            name='target_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xx_entity',
            name='alias_default',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='xx_entity',
            name='parent',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='xx_pivotfund',
            name='actual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='xx_pivotfund',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='xx_pivotfund',
            name='encumbrance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='xx_pivotfund',
            name='fund',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
