# Generated by Django 4.2.7 on 2025-08-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_and_entitys', '0004_alter_xx_account_alias_default_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xx_account',
            name='account',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='xx_account_entity_limit',
            name='account_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='xx_account_entity_limit',
            name='entity_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='xx_entity',
            name='entity',
            field=models.IntegerField(),
        ),
    ]
