# Generated by Django 4.2.7 on 2025-08-08 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_and_entitys', '0005_alter_xx_account_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xx_account_entity_limit',
            name='is_transer_allowed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='xx_account_entity_limit',
            name='is_transer_allowed_for_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='xx_account_entity_limit',
            name='is_transer_allowed_for_target',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
